### ISSUE TITLE
codecData event for multiple inputs

### ISSUE THREAD

**Issue by codingquark** [fluent-ffmpeg/node-fluent-ffmpeg#486] opened 2015-12-18 13:10 UTC
Currently, it seems to me that `codecData` is being fired only once and gives the result of the first input specified.

Is there any way I could get `codecData` output of all the inputs that have been specified?

**Comment by njoyard** [comment] 2015-12-18 22:16
That's not currently possible. In a few weeks we'll implement new event handlers around ffmpeg output, so that will be made easier then!
Currently the only way I see is waiting for the 'end' or 'error' event to fire. Those receive ffmpeg output as their 2nd and 3rd arguments.

**Comment by codingquark** [comment] 2015-12-19 03:38
Oh, OK. I will then make an ffprobe query on the media.

Thanks!

**Comment by njoyard** [comment] 2016-03-16 22:38
Duplicate of #512

**Closed by njoyard** 2016-03-16 22:38 UTC
Labels: Feature
