### ISSUE TITLE
hard crash in /lib/utils.js when 'progress.bitrate' is not defined

### ISSUE THREAD

**Issue by jseeley78** [fluent-ffmpeg/node-fluent-ffmpeg#426] opened 2015-08-11 15:51 UTC
have a recurring issue with fluent ffmpeg hard crashing when certain sources do not return a progress.bitrate (crash listed below).

I tried to create a pull request to add some safety around the .replace, but I didn't have permission to push my branch; Something to the effect of->

line 333 in util.js:
 currentKbps: progress.bitrate ? parseFloat(progress.bitrate.replace('kbits/s', '')) : 0,

CRASH---->
/usr/local/v/node-app/prod-1092/node_modules/fluent-ffmpeg/lib/utils.js:333
        currentKbps: parseFloat(progress.bitrate.replace('kbits/s', '')),
                                                 ^
TypeError: Cannot call method 'replace' of undefined
    at Object.module.exports.extractProgress (/usr/local/v/node-app/prod-1092/node_modules/fluent-ffmpeg/lib/utils.js:333:50)
    at Socket.<anonymous> (/usr/local/v/node-app/prod-1092/node_modules/fluent-ffmpeg/lib/processor.js:510:21)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)

**Comment by njoyard** [comment] 2015-08-12 06:01
Closing this as a duplicate of #406.

**Closed by njoyard** 2015-08-12 06:01 UTC
