### ISSUE TITLE
Issue in taking ios mobile video

### ISSUE THREAD

**Issue by himanshugoyal5734** [fluent-ffmpeg/node-fluent-ffmpeg#509] opened 2016-03-14 12:57 UTC
fluent-ffmpeg can't get the ios mobile video and throw an error :
 "TypeError: Cannot convert undefined or null to object",
    "    at Function.keys (native)",
    "    at /home/himanshu/Documents/weone/BackendAPI/node_modules/fluent-ffmpeg/lib/ffprobe.js:153:40",
    "    at Array.forEach (native)",
    "    at handleExit (/home/himanshu/Documents/weone/BackendAPI/node_modules/fluent-ffmpeg/lib/ffprobe.js:152:46)",
    "    at ChildProcess.<anonymous> (/home/himanshu/Documents/weone/BackendAPI/node_modules/fluent-ffmpeg/lib/ffprobe.js:190:11)",
    "    at emitTwo (events.js:100:13)",
    "    at ChildProcess.emit (events.js:185:7)",
    "    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"
  ],
  "level": "error",
  "message": "uncaughtException: Cannot convert undefined or null to object"
}
I am using in my project and other video are operation are perform successfully except ios video .can anybody help me for this ???

**Comment by njoyard** [comment] 2016-03-14 14:14
Duplicate of #404

**Closed by njoyard** 2016-03-14 14:14 UTC

**Comment by himanshugoyal5734** [comment] 2016-03-15 04:49
sorry i can't getting the solution . can you explain in brief???

**Comment by himanshugoyal5734** [comment] 2016-03-15 05:05
lines = lines.filter(Boolean); to line 15 of /lib/ffprobe.js removes blank entries and fixes it.
