### ISSUE TITLE
Concat question.

### ISSUE THREAD

**Issue by maxfridbe** [fluent-ffmpeg/node-fluent-ffmpeg#496] opened 2016-02-05 23:13 UTC
How can i achieve a command like this:

`ffmpeg -f concat -i mylist.txt -c copy output.mp4`

As Described here: [https://trac.ffmpeg.org/wiki/Concatenate](url)

I tried several of your examples but they resulted in different commands.

**Comment by njoyard** [comment] 2016-02-21 15:40
Have you read the documentation ? Which part of your command do you fail to reproduce ?

**Comment by youran** [comment] 2016-03-26 18:04
mergeToFile() can't do it because it is using a complex filtergraph.
Filtering and streamcopy cannot be used together.

The execution of op's command would be very fast, while mergeToFile() is slow, as it's related to re-encoding.

Is it a way to produce op's command from mergeToFile() or other API?

**Comment by njoyard** [comment] 2016-03-29 17:00
Maybe `ffmpeg('mylist.txt').inputFormat('concat').writeToFile('output.mp4')` should work ?

**Comment by youran** [comment] 2016-03-29 17:14
I've found a working solution:

var fs = require('fs');
var fileList = ['part1.mp4', 'part2.mp4'];     // files to merge
var listFileName = 'list.txt', fileNames = '';

// ffmpeg -f concat -i mylist.txt -c copy output
fileList.forEach(function(fileName, index){
	fileNames = fileNames + 'file ' + '\'' + fileName + '\'\n';
});

fs.writeFileSync(listFileName, fileNames);

var merge = ffmpeg();
merge.input(listFileName)
     .inputOptions(['-f concat', '-safe 0'])
     .outputOptions('-c copy')
     .save('/path/to/merged/file');

**Closed** 2017-01-08 09:35 UTC
Labels: Feedback needed, Question

**Comment by taylorjdawson** [comment] 2019-11-02 20:13
@youran How would you specify the temp folder that is used in merging the videos?

**Comment by PiterJackson** [comment] 2020-04-17 02:59
> @youran How would you specify the temp folder that is used in merging the videos?

It is not necessary to add a temporary file folder.

**Comment by didkivskyy** [comment] 2020-06-27 12:04
**.inputFormat('concat')**  does not work for me (fluent-ffmpeg@2.1.2)
**.mergeToFile()** of course is not what we want as it REencodes the streams.

What does work is an option closer to original ffmpeg syntax:
`.input( 'concat:input1.ext|input2.ext|input3.ext')`
`.audioCodec('copy')`
`.videoCodec('copy')`
`.output('out.ext')`
`.run();`

**Comment by jmonster** [comment] 2020-07-06 17:54
@didkivskyy this is only outputting `input1.ext` as `out.ext` for me -- not the additional files? In my case, I'm trying:
```
concat:/Users/johnny/Downloads/IMG_0837.MOV|/Users/johnny/Downloads/IMG_0838.MOV|/Users/johnny/Downloads/IMG_0839.MOV
```

**Comment by flenoir** [comment] 2020-07-30 09:47
> @didkivskyy this is only outputting `input1.ext` as `out.ext` for me -- not the additional files? In my case, I'm trying:
> 
> ```
> concat:/Users/johnny/Downloads/IMG_0837.MOV|/Users/johnny/Downloads/IMG_0838.MOV|/Users/johnny/Downloads/IMG_0839.MOV
> ```
@jmonster did you manage to concat all files ? i guess i have same issue with only first file as output and no concatenation of others files

**Comment by jmonster** [comment] 2020-07-30 14:46
I believe I got it working following a completely different example, but I think there was a drawback if the codecs were different that method would fail

I lost interest in the experiment I was doing and didn’t pursue the issue any farther
