### ISSUE TITLE
ffprobe uncaughtException: Object.keys called on non-object in ffprobe.js at line 153

### ISSUE THREAD

**Issue by ashwinikd** [fluent-ffmpeg/node-fluent-ffmpeg#453] opened 2015-10-09 08:53 UTC
fluent-ffmpeg version: 2.0.1
```
ffprobe version 2.7.1 Copyright (c) 2007-2015 the FFmpeg developers
built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
```

Happens with following output:

```
[STREAM]
index=0
codec_name=mpeg4
codec_long_name=MPEG-4 part 2
profile=Main Profile
codec_type=video
codec_time_base=1/300
codec_tag_string=mp4v
codec_tag=0x7634706d
width=1920
height=1088
coded_width=1920
coded_height=1088
has_b_frames=1
sample_aspect_ratio=1:1
display_aspect_ratio=30:17
pix_fmt=yuv420p
level=4
color_range=N/A
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
timecode=N/A
refs=1
quarter_sample=0
divx_packed=0
id=N/A
r_frame_rate=50/3
avg_frame_rate=41760000/2508013
time_base=1/90000
start_pts=0
start_time=0.000000
duration_ts=2508013
duration=27.866811
bit_rate=21991887
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=464
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:rotate=90
TAG:creation_time=2014-09-22 10:53:51
TAG:language=eng
TAG:handler_name=VideoHandle
TAG:encoder=                               
[SIDE_DATA]
side_data_type=Display Matrix
side_data_size=36
displaymatrix=
00000000:            0       65536           0
00000001:       -65536           0           0
00000002:            0           0  1073741824

rotation=-90
[/SIDE_DATA]
[/STREAM]
[STREAM]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=HE-AAC
codec_type=audio
codec_time_base=1/24000
codec_tag_string=mp4a
codec_tag=0x6134706d
sample_fmt=fltp
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/48000
start_pts=0
start_time=0.000000
duration_ts=1354160
duration=28.211667
bit_rate=127981
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=661
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
TAG:creation_time=2014-09-22 10:53:51
TAG:language=eng
TAG:handler_name=SoundHandle
[/STREAM]
[FORMAT]
filename=/Volumes/NO NAME/VID_20140922_162351.3gp
nb_streams=2
nb_programs=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=28.202000
size=77097666
bit_rate=21870127
probe_score=100
TAG:major_brand=3gp4
TAG:minor_version=0
TAG:compatible_brands=isom3gp4
TAG:creation_time=2014-09-22 10:53:51
[/FORMAT]
```

Caused by this line in output
```
00000002:            0           0  1073741824
                            <--- Empty line.
rotation=-90
```
` parseFfprobeOutput` stops at this line leaving `data.format` `undefined` causing application to crash here `var legacyTagKeys = Object.keys(target).filter(legacyTag);`.

**Comment by njoyard** [comment] 2015-10-11 08:01
Duplicate of #404. There's a fix available on 'master' branch, not yet released, though.

**Closed by njoyard** 2015-10-11 08:01 UTC
