### ISSUE TITLE
Only one input stream is supported

### ISSUE THREAD

**Issue by danielbanfield** [fluent-ffmpeg/node-fluent-ffmpeg#536] opened 2016-05-01 09:15 UTC
Hi,
Library is serving me well - great job! But I now need to merge multiple input streams into one file/output. 
I see it is purposely not supported "for now":
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/blob/master/doc/inputs.js.html

Any indication as to when it will be, and advice on workarounds or why it is not currently supported?
Thanks
Dan

**Comment by njoyard** [comment] 2016-05-01 10:02
Hi @danielbanfield 

Contrary to what the comments seem to mean, there is no short- or long-term plans to support multiple input streams. Input streams are handled by piping them to ffmpeg process standard input. There is only one standard input, so there you have it :)

In theory, we could handle several stream inputs by piping each of them to a named pipe (UNIX FIFO) and then instructing ffmpeg to read from those pipes. The problem is : nodejs does not support fifos because they have the potential of deadlocking the event loop.

So unfortunately this is currently not possible, and I don't see any way that this could become possible in the future.

**Comment by danielbanfield** [comment] 2016-05-11 09:11
Thanks for the quick reply (I did read it on the day but didn't get round to reply). Good to know the limitation on this to think around the problem. In the end I just 
- streamed from source to disk
- addinput for the files to perform merge
- serve merged file
- cleaned up the files afterward

Since I didn't have a hard requirement for real-time merging.

**Comment by njoyard** [comment] 2016-05-11 09:22
Good to see you found a workaroung. I'm closing this issue, then.

**Closed by njoyard** 2016-05-11 09:22 UTC
Labels: Question

**Comment by adminy** [comment] 2019-07-05 19:51
What about having it in an ArrayBuffer?

**Comment by numman** [comment] 2020-03-10 13:24
What about adding this:
[fluent-ffmpeg-multistream](https://github.com/t-mullen/fluent-ffmpeg-multistream)

**Comment by iFlyinq** [comment] 2024-10-03 09:32
> * addinput for the files to perform merge
